# Generated by Django 4.2.23 on 2025-07-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('kategori', models.CharField(choices=[('Optik Gözlük', 'Optik Gözlük'), ('Güneş Gözlüğü', 'Güneş Gözlüğü'), ('Kontakt Lens', 'Kontakt Lens'), ('Aksesuar', 'Aksesuar'), ('Diğer', 'Diğer')], default='Diğer', max_length=50, verbose_name='Kategori')),
                ('marka', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marka')),
                ('model_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Kodu')),
                ('stok_adedi', models.IntegerField(default=0, verbose_name='Stok Adedi')),
                ('alis_fiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Alış Fiyatı')),
                ('satis_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['ad'],
            },
        ),
    ]
