# Generated by Django 4.2.23 on 2025-07-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0002_kategori_alter_urun_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='StokAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dusuk_stok_esik_1', models.PositiveIntegerField(default=20, verbose_name='Düşük Stok Eşiği (Uyarı 1 - Örn: 20)')),
                ('dusuk_stok_esik_2', models.PositiveIntegerField(default=50, verbose_name='Düşük Stok Eşiği (Uyarı 2 - Örn: 50)')),
            ],
            options={
                'verbose_name': 'Stok Ayarı',
                'verbose_name_plural': 'Stok Ayarları',
            },
        ),
    ]
