# Generated by Django 4.2.23 on 2025-07-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urun', '0002_kategori_alter_urun_kategori'),
        ('musteri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar')),
                ('odenmis_tutar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ödenen Tutar')),
                ('durum', models.CharField(choices=[('Beklemede', 'Beklemede (Ödeme Bekleniyor)'), ('Onaylandı', 'Onaylandı (Üretim/Hazırlık Aşamasında)'), ('Hazır', 'Hazır (Teslimata Hazır)'), ('Teslim Edildi', 'Teslim Edildi'), ('İptal Edildi', 'İptal Edildi')], default='Beklemede', max_length=50, verbose_name='Durum')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('teslimat_tarihi', models.DateField(blank=True, null=True, verbose_name='Tahmini/Gerçek Teslimat Tarihi')),
                ('musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musteri.musteri', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-siparis_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SiparisUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparis_urunleri', to='siparis.siparis', verbose_name='Sipariş')),
                ('urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Ürünü',
                'verbose_name_plural': 'Sipariş Ürünleri',
                'unique_together': {('siparis', 'urun')},
            },
        ),
    ]
