# Generated by Django 4.2.23 on 2025-07-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siparis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='toplam_tutar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Toplam Tutar'),
        ),
    ]
