# Generated by Django 4.2.23 on 2025-07-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siparis', '0002_alter_siparis_toplam_tutar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparisurun',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Birim Fiyat'),
        ),
    ]
