# Generated by Django 4.2.23 on 2025-07-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siparis', '0003_alter_siparisurun_birim_fiyat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiparisUrun',
        ),
    ]
