# Generated by Django 4.2.23 on 2025-07-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siparis', '0004_delete_siparisurun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='odenmis_tutar',
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödenen Miktar')),
                ('odeme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Tarihi')),
                ('odeme_sekli', models.CharField(choices=[('Nakit', 'Nakit'), ('Kredi Kartı', 'Kredi Kartı'), ('Havale/EFT', 'Havale/EFT'), ('Diğer', 'Diğer')], default='Nakit', max_length=50, verbose_name='Ödeme Şekli')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Ödeme Notu')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to='siparis.siparis', verbose_name='İlgili Sipariş')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-odeme_tarihi'],
            },
        ),
    ]
