# Generated by Django 4.2.23 on 2025-07-27 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiderKategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Gider Kategorisi Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Gider Kategorisi',
                'verbose_name_plural': 'Gider Kategorileri',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Gider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('gider_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Gider Tarihi')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('harcanan_kullanicilar', models.ManyToManyField(blank=True, related_name='giderler', to=settings.AUTH_USER_MODEL, verbose_name='Harcanan Kullanıcı(lar)')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='giderler.giderkategorisi', verbose_name='Gider Kategorisi')),
            ],
            options={
                'verbose_name': 'Gider',
                'verbose_name_plural': 'Giderler',
                'ordering': ['-gider_tarihi'],
            },
        ),
    ]
