# Generated by Django 4.2.23 on 2025-07-27 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giderler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gider',
            name='harcanan_kullanicilar',
            field=models.ManyToManyField(blank=True, related_name='giderler', to=settings.AUTH_USER_MODEL, verbose_name='Harcayan Kullanıcı(lar)'),
        ),
        migrations.AlterField(
            model_name='gider',
            name='miktar',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar'),
        ),
    ]
