# Generated by Django 4.2.23 on 2025-07-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Adı')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('eposta', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('dogum_tarihi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['-kayit_tarihi'],
            },
        ),
    ]
