# Generated by Django 4.2.23 on 2025-07-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musteri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Satış Tarihi')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar')),
                ('odeme_sekli', models.CharField(choices=[('Nakit', 'Nakit'), ('Kredi Kartı', 'Kredi Kartı'), ('Havale/EFT', 'Havale/EFT'), ('Diğer', 'Diğer')], default='Nakit', max_length=50, verbose_name='Ödeme Şekli')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musteri.musteri', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Satış',
                'verbose_name_plural': 'Satışlar',
                'ordering': ['-satis_tarihi'],
            },
        ),
    ]
