# Generated by Django 4.2.23 on 2025-07-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0002_kategori_alter_urun_kategori'),
        ('satis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satis',
            name='toplam_tutar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Toplam Tutar'),
        ),
        migrations.CreateModel(
            name='SatisUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Birim Fiyat')),
                ('satis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satis_urunleri', to='satis.satis', verbose_name='Satış')),
                ('urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Satış Ürünü',
                'verbose_name_plural': 'Satış Ürünleri',
                'unique_together': {('satis', 'urun')},
            },
        ),
    ]
