# Generated by Django 4.2.23 on 2025-07-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satis', '0002_alter_satis_toplam_tutar_satisurun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satis',
            name='toplam_tutar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Toplam Tutar (Manuel/Hesaplanan)'),
        ),
        migrations.CreateModel(
            name='SatisOdeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödenen Miktar')),
                ('odeme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Tarihi')),
                ('odeme_sekli', models.CharField(choices=[('Nakit', 'Nakit'), ('Kredi Kartı', 'Kredi Kartı'), ('Havale/EFT', 'Havale/EFT'), ('Diğer', 'Diğer')], default='Nakit', max_length=50, verbose_name='Ödeme Şekli')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Ödeme Notu')),
                ('satis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satis_odemeleri', to='satis.satis', verbose_name='İlgili Satış')),
            ],
            options={
                'verbose_name': 'Satış Ödemesi',
                'verbose_name_plural': 'Satış Ödemeleri',
                'ordering': ['-odeme_tarihi'],
            },
        ),
    ]
