"""
Django settings for Web project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5%3a@fm6qr9ddvszjwp^8o2jc31+ebeqj$o(jjgwsxc6w!d$i!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
X_FRAME_OPTIONS = 'SAMEORIGIN'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'musteri',
    'satis',
    'urun',
    'siparis',
    'giderler',
    'core_utils'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # 'staticfiles' genellikle kullanılan bir isimdir


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py dosyanızda bu blokları bulun ve mevcutlarını bununla değiştirin

JAZZMIN_SETTINGS = {
    # Navbar özelleştirme
    "topmenu_links": [
        # Ana Sayfa butonu (Jazzmin varsayılan admin ana sayfasına yönlendirir)
        {"name": "Ana Sayfa", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Tüm Siparişler", "url": "admin:siparis_siparis_changelist", "permissions": ["siparis.view_siparis"]},
        # Yeni Sipariş butonu
        # Kendi projenizdeki URL'ye göre ayarlayın
        {"name": "Yeni Sipariş", "url": "/admin/siparis/siparis/add/", "permissions": ["siparis.add_siparis"]},

        # Yeni Satış butonu
        # Kendi projenizdeki URL'ye göre ayarlayın
        {"name": "Yeni Satış", "url": "/admin/satis/satis/add/", "permissions": ["satis.add_satis"]},

        # Tüm Siparişler butonu (Sipariş modelinin listeleme sayfasına yönlendirir)
        # Kendi projenizdeki uygulama ve model adına göre ayarlayın
        
    ],

    "site_title": "Optik Yönetim Paneli", # Projenizin adını buraya girin
    "site_header": "Optik Yönetim Sistemi", # Projenizin başlığını buraya girin
    "site_brand": "Optik ERP", # Projenizin marka adını buraya girin
    
    # Logonuzun path'i (örneğin 'images/your_logo.png' static klasörünüzde olmalı)
    "site_logo": "images/logo_optik_2.png",
    "login_logo": "images/logo_optik_1.png",
    "login_logo_dark": "images/logo_optik_1.png",
    
    "welcome_sign": "Optik Yönetim Paneline Hoş Geldiniz", # Kendi karşılama mesajınızı girin
    "copyright": "Optik Yönetim © 2025", # Kendi telif hakkı bilginizi girin
    "ui_style": "flat", # Bu, tasarımın düz ve modern görünümünü sağlar
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": [],
    "hide_models": [],
    
    # Uygulama ve model sıralaması (kendi uygulamanızın adlarına göre güncelleyin!)
    "order_with_respect_to": [
        "auth",
        "musteri", # Örnek uygulama adı
        "urun",    # Örnek uygulama adı
        "siparis", # Örnek uygulama adı
        "satis",   # Örnek uygulama adı
        "giderler", # Örnek uygulama adı
        # Diğer uygulama adlarınızı buraya ekleyin
    ], 
    
    # Kendi custom CSS ve JS dosyalarınızı buraya ekleyebilirsiniz (örn: "css/custom_admin.css")
    # Eğer sorun yaşıyorsanız şimdilik None bırakmak iyi bir pratiktir.
    "custom_css": None,
    "custom_js": None,
    
    "use_google_fonts_cdn": True,
    "show_ui_builder": True, # UI Builder'ı görmek isterseniz True bırakın
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    
    # İkonlar (uygulama adlarınıza göre güncelleyin!)
    "icons": {
        "auth": "fas fa-users-cog",
        "musteri": "fas fa-users",
        "urun": "fas fa-box-open",
        "siparis": "fas fa-clipboard-list",
        "satis": "fas fa-handshake",
        "giderler": "fas fa-dollar-sign",
        # Diğer uygulamalarınız için ikonlar ekleyebilirsiniz
    },
    
    # UI Tweaks ayarları (Buradaki bazı ayarlar JAZZMIN_UI_TWEAKS ile çakışabilir,
    # genellikle JAZZMIN_UI_TWEAKS daha önceliklidir.)
    "ui_tweaks": {
        "theme": "united", # Ana tema
        "dark_mode_theme": None, # Koyu mod kapalı
        "navbar": "navbar-light", # Navbar rengi (açık)
        "accent": "accent-lightblue", # Vurgu rengi
        "sidebar": "sidebar-light-danger", # Sidebar rengi (açık, tehlike vurgulu)
        "brand_colour": "navbar-light", # Marka rengi
        "button_classes": {
            "primary": "btn-outline-primary",
            "secondary": "btn-outline-secondary",
            "info": "btn-info",
            "warning": "btn-warning",
            "danger": "btn-danger",
            "success": "btn-success"
        }
    },
    
    # Yan menüdeki özel gruplandırmalar ve bağlantılar (kendi uygulama ve modellerinize göre uyarlayın!)
    "custom_links": {
        "musteri": [ # Eğer müşteri uygulamanızın adı 'musteri' ise
            {
                "name": "Müşteri İşlemleri",
                "models": [
                    "musteri.Musteri", # 'musteri' uygulamasındaki 'Musteri' modeli
                    # "musteri.Adres", # Eğer varsa, örnek model
                ]
            },
        ],
        "siparis": [ # Eğer sipariş uygulamanızın adı 'siparis' ise
            {
                "name": "Sipariş İşlemleri",
                "models": [
                    "siparis.Siparis",
                    "siparis.Odeme", # Örnek model
                ]
            },
        ],
        # Diğer uygulamalarınız için benzer şekilde custom linkler ekleyebilirsiniz
    }
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-light", # Jazzmin settings içinde de var, burada öncelikli
    "accent": "accent-lightblue", # Jazzmin settings içinde de var, burada öncelikli
    "navbar": "navbar-light", # Jazzmin settings içinde de var, burada öncelikli
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False, # Sidebar'ın sabit kalıp kalmayacağı
    "sidebar": "sidebar-light-danger", # Jazzmin settings içinde de var, burada öncelikli
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False, # Sidebar'ın genişlemesini kapatma
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "united", # Ana tema (Jazzmin settings içinde de var, burada öncelikli)
    "dark_mode_theme": None, # Koyu mod kapalı
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}